### ISSUE TITLE
Ability to decode an encoded transaction

### ISSUE THREAD

**Issue by manthanhd** [xyield/xrpl-go#34]
Hey, 

I see there is support for Encode in the binarycodec but any idea when you will be able to support the decode method? I have a use-case where I am looking to decode a given encoded, unsigned transaction.

Thanks,
MD

**Comment by joshwalong** [comment]
Hey MD,
The Decode method is in the [wip-tojson](https://github.com/xyield/xrpl-go/tree/wip-tojson) branch currently in PR but  you could try it there for now until it's merged.
Thanks,
J

**Comment by joshwalong** [comment]
Hi again Manthan,
Decode is now supported on 'main'
Hope this helps with your use-case
Cheers
