### ISSUE TITLE
Need Help with Locally Signing "AccountSet" Operation

### ISSUE THREAD

**Issue by LucasDGS** [xyield/xrpl-go#44]
Hello,
I'm trying to locally sign an "AccountSet" operation to require a destination tag for an XRP address using the xyield/xrpl-go, but I'm encountering some difficulties.

What I'm trying to achieve:

I want to set the flag for "Require Destination Tags" on my XRP address.

What I've tried:
 I've looked into the library but I haven't been able to identify which methods I should use to sign locally. I'm not very familiar with it. 
 
 How can I locally sign the "AccountSet" operation using this library?

**Comment by CreatureDev** [comment]
Encode the transaction into json using the standard json encoding library, and pass it to the Sign method found in keypairs/keypairs.go
