### ISSUE TITLE
getting the tx_blob after sign

### ISSUE THREAD

**Issue by arthures11** [xyield/xrpl-go#49]
After signing the payment transaction using Sign function from keypairs, the output seems to be way too short and not even similiar to the wanted tx_blob binary chunk.

Is there any other function that would help me receive one?

Thank you in advance

**Comment by CreatureDev** [comment]
Check my fork to see if it is functioning as you expect https://github.com/CreatureDev/xrpl-go
I have not been able to get into contact with the xyield team about finishing up encoding and signing, so I continued work on my own
That said I have not had time recently to continue development. I hope to get back around to it eventually.

**Comment by arthures11** [comment]
> Check my fork to see if it is functioning as you expect https://github.com/CreatureDev/xrpl-go I have not been able to get into contact with the xyield team about finishing up encoding and signing, so I continued work on my own That said I have not had time recently to continue development. I hope to get back around to it eventually.

looking definitely richer than this one, however here is my question:
assuming ive received this kind of otput

E83CAFEAF100793F0C6570D60C7447FF3A87E0DC0CAE9AD90EF0102860EC3BD1D20F432494021F3E19DAFF257A420CA64A49C283AB5AD00B6B0CEA1756151C01 

after Sign (example output from TestSign), how can i now use it as a tx_blob which is usually looking this way (example);

120000228000000024002506BD6140000000000003E868400000000000000D73210385A4FBB67DCABBFAA13D371B3ED155D136483F74D82B03DF0EF8688F56033B8474473045022100CA6244EB406DB2C1791D265E6D25F9F5B130C4B94EEFF58D9CE3525F782168B002201383AB3B37FA66F5986FA6380728E8DDF3D364A2DF16A6647FC5C2901274348C81143BF6E46A8F9BC49B65706DA36BA4D3044E4BE40B831479A2A3B3AF517775109D089D4BD3D9487066DF14

would "encode" method be sufficient alone?

**Comment by CreatureDev** [comment]
The signature needs to be added to the transaction struct, then encode the transaction
The signature is not the transaction, it's just used to validate the transaction
Here is an example of signing and submitting a transaction
```
	tx := &transactions.Payment{
		BaseTx: transactions.BaseTx{
			Account:         types.Address(src),
			TransactionType: transactions.PaymentTx,
			Fee:             types.XRPCurrencyAmount(10),
			SigningPubKey:   pubKey,
			Sequence:        seq,
			Flags:           types.SetFlag(0),
		},
		Destination: types.Address(dst),
		Amount:      types.XRPCurrencyAmount(100),
	}
	enc, err := binarycodec.EncodeForSigning(tx)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	sig, err := keypairs.Sign(enc, privKey)
	tx.BaseTx.TxnSignature = sig
	sub := txModel.SubmitRequest{}
	sub.TxBlob, err = binarycodec.Encode(tx)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	res, s, err := cl.Transaction.Submit(&sub)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	fmt.Printf("RESPONSE %+v\n", res.Tx)
```

**Comment by arthures11** [comment]
> The signature needs to be added to the transaction struct, then encode the transaction The signature is not the transaction, it's just used to validate the transaction Here is an example of signing and submitting a transaction `tx := &transactions.Payment{ BaseTx: transactions.BaseTx{ Account: types.Address(src), TransactionType: transactions.PaymentTx, Fee: types.XRPCurrencyAmount(10), SigningPubKey: pubKey, Sequence: seq, Flags: types.SetFlag(0), }, Destination: types.Address(dst), Amount: types.XRPCurrencyAmount(100), } enc, err := binarycodec.EncodeForSigning(tx) if err != nil { fmt.Println(err.Error()) os.Exit(1) } sig, err := keypairs.Sign(enc, privKey) tx.BaseTx.TxnSignature = sig sub := txModel.SubmitRequest{} sub.TxBlob, err = binarycodec.Encode(tx) if err != nil { fmt.Println(err.Error()) os.Exit(1) } res, s, err := cl.Transaction.Submit(&sub) if err != nil { fmt.Println(err.Error()) os.Exit(1) } fmt.Printf("RESPONSE %+v\n", res.Tx)`

i see, however as far as ive checked i will be unable to use it
the only way to sign is the ed25519, my xrp address uses ecdsa, so apparently i wont be able to do anything here :(

**Comment by CreatureDev** [comment]
> i will be unable to use it the only way to sign is the ed25519, my xrp address uses ecdsa, so apparently i wont be able to do anything here :(

Yeah you will either need to create a new account, or add a new ed25519 key to your existing account using the SetRegularKey transaction
We also do have an interface you can implement to add support for an additional crypto algorithm, if you want to add it yourself. Take a look at keypairs/ed25519.go for an example of how it's done.

**Comment by arthures11** [comment]
> > i will be unable to use it the only way to sign is the ed25519, my xrp address uses ecdsa, so apparently i wont be able to do anything here :(
> 
> Yeah you will either need to create a new account, or add a new ed25519 key to your existing account using the SetRegularKey transaction We also do have an interface you can implement to add support for an additional crypto algorithm, if you want to add it yourself. Take a look at keypairs/ed25519.go for an example of how it's done.

i dont have to change anything in terms of last encoding (signed tx) into a blob right? just sign differently?
because after implementing ecdsa i am getting response from ledger that suggests signature is wrong/invalid.

**Comment by arthures11** [comment]
code for reference:

```
func SignSECEP256K1 (tx []byte, privKeyHex string) (string, error) {
	// decode the private key
	privKeyBytes, err := hex.DecodeString(privKeyHex)
	if err != nil {
		return "", errors.New("invalid private key hex")
	}
	// remove the '00' prefix if it exists
	if len(privKeyBytes) > 0 && privKeyBytes[0] == 0x00 {
		privKeyBytes = privKeyBytes[1:]
	}

	// parse the private key
	privKey, _ := btcec.PrivKeyFromBytes(btcec.S256(), privKeyBytes)

	// sign the transaction directly
	signature, err := privKey.Sign(tx) 
	if err != nil {
		return "", errors.New("failed to sign transaction")
	}

	// serialize signature to DER format
	derSignature := signature.Serialize()

	// return the DER-encoded signature as a hex string
	return hex.EncodeToString(derSignature), nil
}
```

after this, i simply add the signature and then encode it:

	tx2.BaseTx.TxnSignature = signature //(returned out of SignSECEP256K1() i showed above)
	
	TxBlob := binarycodec.Encode(tx2) //final tx_blob

**Comment by CreatureDev** [comment]
hex.Decode should no longer be necessary on my fork, just use the output of EncodeForSigning as is

**Comment by arthures11** [comment]
unfortunately i can't make it work.

i made it work however with **[github.com/rubblelabs/ripple](https://github.com/rubblelabs/ripple)**
as they have ECDSA signing there, i had to make some changes (like manually setting the public key every tx) but in the end it works.
